[pytest]
pythonpath = .
filterwarnings =
    ignore::RuntimeWarning:sklearn.*
    ignore::DeprecationWarning:matplotlib.*
    ignore::PendingDeprecationWarning:matplotlib.*
    ignore:urllib3 v2 only supports OpenSSL:Warning
    ignore::pydantic.warnings.PydanticDeprecatedSince212
    ignore::sqlalchemy.exc.LegacyAPIWarning
